### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by pramodhrachuri** [TheRealMentor/TheRealMentor.github.io#1]
Gallery me ye wali photo nahi daala tumne

![whatsapp image 2018-06-21 at 5 56 32 pm](https://user-images.githubusercontent.com/13718503/42492287-27081b98-8436-11e8-825f-3b5959b49bd4.jpeg)

**Comment by pramodhrachuri** [comment]
Reply toh kar!!

**Comment by TheRealMentor** [comment]
Bhag Saale
